GET http://localhost:9865/users

###

GET http://localhost:9865/users/60bd2b305d76583c1ce1c4af

###

// Sign Up
POST http://localhost:9865/users
Content-Type: application/json

{
  "username": "John",
  "password": "password"
}

###

PATCH http://localhost:9865/users/60bd46fbefb94713101004c9
Content-Type: application/json

{
  "username": "John",
  "role": "admin"
}

###

// Login
POST http://localhost:9865/users/login
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

###

DELETE http://localhost:9865/users

###

DELETE http://localhost:9865/users/60bd44b28ca1aa3648327214