GET http://localhost:9865/users

###

GET http://localhost:9865/users/60be7c19088fd02cc8ffe20c

###

GET http://localhost:9865/users/username/aa


###

// Sign Up
POST http://localhost:9865/users
Content-Type: application/json

{
  "username": "b",
  "password": "a"
}

###

PATCH http://localhost:9865/users/60bd46fbefb94713101004c9
Content-Type: application/json

{
  "username": "John",
  "role": "admin"
}

###

// Login
POST http://localhost:9865/users/login
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

###

DELETE http://localhost:9865/users

###

DELETE http://localhost:9865/users/6191594633e9e22f5c15cd10